import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// ⚡ CACHE PUBLIC API CALLS
registerRoute(
    /^https?:\/\/.*\/api\/public\/barberias\/.*/i,
    new NetworkFirst({
        cacheName: 'public-api-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 60 * 60 * 24, // 24 hours
            }),
        ],
        networkTimeoutSeconds: 5,
    })
);

// Handle Push Notifications
self.addEventListener('push', (event) => {
    if (!event.data) return;

    try {
        const payload = event.data.json();
        const { title, body, icon, badge, data } = payload;

        const options = {
            body: body || '',
            icon: icon || '/icon-192.png',
            badge: badge || '/icon-192.png',
            data: data || {},
            vibrate: [100, 50, 100],
            actions: [
                { action: 'open', title: 'Ver Agenda' },
                { action: 'close', title: 'Cerrar' }
            ]
        };

        event.waitUntil(
            self.registration.showNotification(title || 'Barber SaaS', options)
        );
    } catch (err) {
        console.error('[SW] Error parsing push data:', err);
    }
});

// Handle Notification Click
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    const urlToOpen = event.notification.data?.url || '/';

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // If no window is open, open a new one
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});
